<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Session;

class FileUploader extends Model
{
    use HasFactory;

    public static function upload($uploaded_file, $upload_to, $width = null, $height = null, $optimized_width = 250, $optimized_height = null)
    {
        // Explanation: $upload_file = this is the uploaded temp file => $request->video_feild_name
        // Explanation: $upload_to = "public/storage/video" OR "public/storage/video/Sj8Ro5Gksde3T.mp4" OR "sdsdncts7sn.png" OR empty if amazon s3 is active
        // Explanation: $width and $height => Image width and height
        // Explanation: $optimized_width and $optimized_height ultra optimization, That is stored in optimized folder

        if (!$uploaded_file)
            return;

        if (!extension_loaded('fileinfo')) {
            Session::flash('error', get_phrase('Please enable fileinfo extension on your server.'));
            return;
        }

        if (!extension_loaded('exif')) {
            Session::flash('error', get_phrase('Please enable exif extension on your server.'));
            return;
        }

        //Add public path
        $upload_path = $upload_to;
        $upload_to = public_path($upload_to);

        $s3_keys = get_settings('amazon_s3', 'object');
        if (empty($s3_keys) || $s3_keys->active != 1) {
            if (is_dir($upload_to)) {
                $file_name = time() . '-' . random(30) . '.' . $uploaded_file->extension();
                $upload_path = $upload_path.'/'.$file_name;
            } else {
                $uploaded_path_arr = explode('/', $upload_to);
                $file_name = end($uploaded_path_arr);
                $upload_to = str_replace('/' . $file_name, "", $upload_to);
                if (!is_dir($upload_to)) {
                    Storage::makeDirectory($upload_to);
                }
            }

            if ($width == null) {
                $uploaded_file->move($upload_to, $file_name);
            } else {

                //Image optimization
                Image::make($uploaded_file->path())->orientate()->resize($width, $height, function ($constraint) {
                    $constraint->upsize();
                    $constraint->aspectRatio();
                })->save($upload_to . '/' . $file_name);

                //Ultra Image optimization
                $optimized_path = $upload_to . '/optimized';
                if (is_dir($optimized_path)) {
                    //Image optimization
                    Image::make($uploaded_file->path())->orientate()->resize($optimized_width, $optimized_height, function ($constraint) {
                        $constraint->upsize();
                        $constraint->aspectRatio();
                    })->save($optimized_path . '/' . $file_name);
                }
            }

            return $upload_path;
        } else {
            //upload to amazon s3
            ini_set('max_execution_time', '600');
            config(['filesystems.disks.s3.key' => $s3_keys->AWS_ACCESS_KEY_ID]);
            config(['filesystems.disks.s3.secret' => $s3_keys->AWS_SECRET_ACCESS_KEY]);
            config(['filesystems.disks.s3.region' => $s3_keys->AWS_DEFAULT_REGION]);
            config(['filesystems.disks.s3.bucket' => $s3_keys->AWS_BUCKET]);

            //social-files this directory automatically created on S3 server, the file upload in this folder
            //The file name generated by laravel s3 package
            $s3_file_path = Storage::disk('s3')->put('social-files', $uploaded_file, 'public');
            $s3_file_path = Storage::disk('s3')->url($s3_file_path);
            return $s3_file_path;
        }
    }

    /**
     * Upload and optimize image for listing images using native PHP GD
     * 
     * @param \Illuminate\Http\UploadedFile $uploadedFile The uploaded file
     * @param string $path Relative path from public (e.g., 'uploads/listing-images')
     * @param string $baseFileName The desired filename (e.g., '0-1234567890.jpg')
     * @return string The final filename
     */
    public static function uploadOptimized($uploadedFile, $path, $baseFileName)
    {
        if (!$uploadedFile) {
            return null;
        }

        $fullPath = public_path($path);
        
        // Ensure directory exists
        if (!is_dir($fullPath)) {
            if (!mkdir($fullPath, 0755, true) && !is_dir($fullPath)) {
                Session::flash('error', get_phrase('Failed to create upload directory.'));
                return null;
            }
        }

        $finalPath = $fullPath . '/' . $baseFileName;

        // Check if GD extension is available
        if (!extension_loaded('gd')) {
            // Fallback to simple move if GD is not available
            try {
                $uploadedFile->move($fullPath, $baseFileName);
                return $baseFileName;
            } catch (\Exception $e) {
                Session::flash('error', get_phrase('Image upload failed.'));
                return null;
            }
        }

        // Get file path and detect image type
        $tempPath = $uploadedFile->path();
        $imageInfo = @getimagesize($tempPath);
        
        // If not a valid image, just move the file as-is
        if ($imageInfo === false) {
            try {
                $uploadedFile->move($fullPath, $baseFileName);
                return $baseFileName;
            } catch (\Exception $e) {
                Session::flash('error', get_phrase('File upload failed.'));
                return null;
            }
        }

        $imageType = $imageInfo[2]; // IMAGETYPE_JPEG, IMAGETYPE_PNG, IMAGETYPE_GIF
        $originalWidth = $imageInfo[0];
        $originalHeight = $imageInfo[1];

        try {
            $maxWidth = 800;
            $maxFileSize = 120 * 1024; // 120 KB in bytes

            // Calculate new dimensions (max width 800px, keep aspect ratio, no upscaling)
            if ($originalWidth > $maxWidth) {
                $newWidth = $maxWidth;
                $newHeight = (int) ($originalHeight * ($maxWidth / $originalWidth));
            } else {
                // No upscaling - keep original size if smaller
                $newWidth = $originalWidth;
                $newHeight = $originalHeight;
            }

            // Load source image based on type
            $sourceImage = null;
            if ($imageType == IMAGETYPE_JPEG) {
                $sourceImage = @imagecreatefromjpeg($tempPath);
            } elseif ($imageType == IMAGETYPE_PNG) {
                $sourceImage = @imagecreatefrompng($tempPath);
            } elseif ($imageType == IMAGETYPE_GIF) {
                $sourceImage = @imagecreatefromgif($tempPath);
            } else {
                // Unsupported image type, fallback to simple move
                $uploadedFile->move($fullPath, $baseFileName);
                return $baseFileName;
            }

            if ($sourceImage === false) {
                throw new \Exception('Failed to load image');
            }

            // Create new image with calculated dimensions
            $newImage = imagecreatetruecolor($newWidth, $newHeight);

            // Preserve transparency for PNG and GIF
            if ($imageType == IMAGETYPE_PNG || $imageType == IMAGETYPE_GIF) {
                imagealphablending($newImage, false);
                imagesavealpha($newImage, true);
                $transparent = imagecolorallocatealpha($newImage, 255, 255, 255, 127);
                imagefilledrectangle($newImage, 0, 0, $newWidth, $newHeight, $transparent);
            }

            // Resize image
            imagecopyresampled(
                $newImage, $sourceImage,
                0, 0, 0, 0,
                $newWidth, $newHeight,
                $originalWidth, $originalHeight
            );

            // Handle JPEG with quality compression loop
            if ($imageType == IMAGETYPE_JPEG) {
                $minQuality = 40;
                $maxQuality = 85;
                $qualityStep = 5;
                $bestQuality = $maxQuality;
                $bestBuffer = null;
                $bestFileSize = null;

                // Try different quality levels
                for ($quality = $maxQuality; $quality >= $minQuality; $quality -= $qualityStep) {
                    // Start output buffering
                    ob_start();
                    imagejpeg($newImage, null, $quality);
                    $buffer = ob_get_clean();
                    $fileSize = strlen($buffer);

                    // If we found a quality that meets our size requirement, use it
                    if ($fileSize <= $maxFileSize) {
                        $bestQuality = $quality;
                        $bestBuffer = $buffer;
                        $bestFileSize = $fileSize;
                        break;
                    }

                    // Track the best quality so far (smallest file size)
                    if ($bestFileSize === null || $fileSize < $bestFileSize) {
                        $bestQuality = $quality;
                        $bestBuffer = $buffer;
                        $bestFileSize = $fileSize;
                    }
                }

                // Save final image with best quality buffer
                if ($bestBuffer !== null) {
                    file_put_contents($finalPath, $bestBuffer);
                } else {
                    // Fallback: save directly
                    imagejpeg($newImage, $finalPath, $bestQuality);
                }
            } elseif ($imageType == IMAGETYPE_PNG) {
                // PNG: save with compression level 6 (good balance)
                imagepng($newImage, $finalPath, 6);
            } elseif ($imageType == IMAGETYPE_GIF) {
                // GIF: save as-is
                imagegif($newImage, $finalPath);
            }

            // Clean up memory
            imagedestroy($sourceImage);
            imagedestroy($newImage);

            return $baseFileName;

        } catch (\Exception $e) {
            // Fallback to simple move if optimization fails
            try {
                $uploadedFile->move($fullPath, $baseFileName);
                return $baseFileName;
            } catch (\Exception $fallbackException) {
                Session::flash('error', get_phrase('Image upload failed.'));
                return null;
            }
        }
    }
}
